#!/bin/sh
real_vice="/opt/homebrew/bin/x64sc"
out=""
replace_next=0
printf "%s\n" "$*" > /tmp/readyos_vice8mb_args.log
for arg in "$@"; do
  if [ "$replace_next" = "1" ]; then
    out="$out '8192'"
    replace_next=0
    continue
  fi
  if [ "$arg" = "-reusize" ]; then
    out="$out '-reusize'"
    replace_next=1
    continue
  fi
  safe=$(printf "%s" "$arg" | sed "s/'/'\\\\''/g")
  out="$out '$safe'"
done
printf "%s\n" "$out" > /tmp/readyos_vice8mb_rewritten_args.log
eval "exec \"$real_vice\" $out"
