#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from readme_lite_common import (
    STYLE_BOLD,
    STYLE_ITALIC,
    STYLE_NORMAL,
    parse_markdown_lite,
)


MARK_PREFIX = "~"
MARK_BOLD = "B"
MARK_ITALIC = "I"


def c_escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        else:
            out.append(ch)
    return "".join(out)


def encode_line(line) -> tuple[int, str]:
    base_style = STYLE_NORMAL
    for st in line.styles:
        if st not in (STYLE_BOLD, STYLE_ITALIC):
            base_style = st
            break

    out_chars = []
    mode = 0  # 0=base, 1=bold, 2=italic

    for ch, st in zip(line.text, line.styles):
        if st == STYLE_BOLD:
            want = 1
        elif st == STYLE_ITALIC:
            want = 2
        else:
            want = 0

        if mode == 1 and want != 1:
            out_chars.append(MARK_PREFIX + MARK_BOLD)
            mode = 0
        elif mode == 2 and want != 2:
            out_chars.append(MARK_PREFIX + MARK_ITALIC)
            mode = 0

        if mode == 0 and want == 1:
            out_chars.append(MARK_PREFIX + MARK_BOLD)
            mode = 1
        elif mode == 0 and want == 2:
            out_chars.append(MARK_PREFIX + MARK_ITALIC)
            mode = 2

        if ch == MARK_PREFIX:
            out_chars.append(MARK_PREFIX + MARK_PREFIX)
        else:
            out_chars.append(ch)

    if mode == 1:
        out_chars.append(MARK_PREFIX + MARK_BOLD)
    elif mode == 2:
        out_chars.append(MARK_PREFIX + MARK_ITALIC)

    return base_style, "".join(out_chars)


def write_header(path: Path, page_count: int, lines_per_page: int, width: int) -> None:
    content = f"""/* Auto-generated by build_support/build_readme_app_assets.py. Do not edit manually. */
#ifndef READYOS_README_PAGES_H
#define READYOS_README_PAGES_H

#define README_PAGE_COUNT {page_count}
#define README_LINES_PER_PAGE {lines_per_page}
#define README_LINE_WIDTH {width}
#define README_MARK_PREFIX '{MARK_PREFIX}'
#define README_MARK_BOLD '{MARK_BOLD}'
#define README_MARK_ITALIC '{MARK_ITALIC}'

#define README_STYLE_NORMAL 0
#define README_STYLE_H1 1
#define README_STYLE_H2 2
#define README_STYLE_H3 3
#define README_STYLE_BOLD 4
#define README_STYLE_ITALIC 5

extern const char *const readme_page_line_text[README_PAGE_COUNT][README_LINES_PER_PAGE];
extern const unsigned char readme_page_line_style[README_PAGE_COUNT][README_LINES_PER_PAGE];

#endif /* READYOS_README_PAGES_H */
"""
    path.write_text(content, encoding="utf-8")


def write_source(path: Path, pages, lines_per_page: int, width: int, header_name: str) -> None:
    lines = []
    lines.append("/* Auto-generated by build_support/build_readme_app_assets.py. Do not edit manually. */")
    lines.append(f"#include \"{header_name}\"")
    lines.append("")

    lines.append("const char *const readme_page_line_text[README_PAGE_COUNT][README_LINES_PER_PAGE] = {")
    for page in pages:
        lines.append("    {")
        for line in page:
            _base_style, encoded = encode_line(line)
            lines.append(f'        "{c_escape(encoded)}",')
        lines.append("    },")
    lines.append("};")
    lines.append("")

    lines.append("const unsigned char readme_page_line_style[README_PAGE_COUNT][README_LINES_PER_PAGE] = {")
    for page in pages:
        lines.append("    {")
        for line in page:
            base_style, _encoded = encode_line(line)
            lines.append(f"        {base_style},")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate hardcoded README app page data from markdown-lite")
    parser.add_argument("--input", required=True, help="Input markdown-lite path")
    parser.add_argument("--out-h", required=True, help="Output header path")
    parser.add_argument("--out-c", required=True, help="Output C source path")
    parser.add_argument("--width", type=int, default=38, help="Content line width")
    parser.add_argument("--lines-per-page", type=int, default=18, help="Content lines per page")
    args = parser.parse_args()

    in_path = Path(args.input)
    out_h = Path(args.out_h)
    out_c = Path(args.out_c)

    content = in_path.read_text(encoding="utf-8")
    pages = parse_markdown_lite(content, width=args.width, lines_per_page=args.lines_per_page)

    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_c.parent.mkdir(parents=True, exist_ok=True)

    write_header(out_h, page_count=len(pages), lines_per_page=args.lines_per_page, width=args.width)
    write_source(out_c, pages, lines_per_page=args.lines_per_page, width=args.width, header_name=out_h.name)

    print(f"Generated {len(pages)} page(s): {out_h} and {out_c}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
