#!/usr/bin/env python3
"""
ReadyOS EasyFlash build helpers.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

import build_apps_catalog_petscii as apps_catalog
import readyos_profiles


ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = ROOT / "bin"
OBJ_DIR = ROOT / "obj"
GEN_DIR = ROOT / "src" / "generated"
RELEASES_DIR = ROOT / "releases"

EASYFLASH_BANK_BYTES = 0x4000
EASYFLASH_LOW_BYTES = 0x2000
EASYFLASH_PAYLOAD_SLOT_BYTES = 0x4000
EASYFLASH_TOTAL_BANKS = 64
EASYFLASH_TOTAL_BYTES = EASYFLASH_TOTAL_BANKS * EASYFLASH_BANK_BYTES
APP_LOAD_START = 0x1000
APP_SNAPSHOT_SIZE = 0xB600
READYSHELL_OVL_LOAD = 0x8E00
READYSHELL_OVL_SLOT_LEN = 0x3800
READYSHELL_OVL_META_OFF = 0x4880F0
READYSHELL_OVL_META_VERSION = 2
READYSHELL_OVL_META_VALID_MASK = 0xFF
READYSHELL_CACHE_BANK = 0x40
READYSHELL_CACHE_BANK2 = 0x41

OVERLAY_SPECS = (
    ("rsparser", "bin/rsparser.prg", READYSHELL_CACHE_BANK, 0x0000, 0x01),
    ("rsvm", "bin/rsvm.prg", READYSHELL_CACHE_BANK, 0x3800, 0x02),
    ("rsdrvilst", "bin/rsdrvilst.prg", READYSHELL_CACHE_BANK, 0x7000, 0x04),
    ("rsldv", "bin/rsldv.prg", READYSHELL_CACHE_BANK2, 0x0000, 0x08),
    ("rsstv", "bin/rsstv.prg", READYSHELL_CACHE_BANK, 0xA800, 0x10),
    ("rsfops", "bin/rsfops.prg", READYSHELL_CACHE_BANK2, 0x3800, 0x20),
    ("rscat", "bin/rscat.prg", READYSHELL_CACHE_BANK2, 0x7000, 0x40),
    ("rscopy", "bin/rscopy.prg", READYSHELL_CACHE_BANK2, 0xA800, 0x80),
)

REPORT_SYMBOLS = "123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


def fail(message: str) -> None:
    raise ValueError(message)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def run(cmd: List[str], *, cwd: Path | None = None) -> None:
    subprocess.run(cmd, cwd=str(cwd or ROOT), check=True, text=True)


def force_easyflash_subtype(crt_path: Path, subtype: int) -> None:
    data = bytearray(crt_path.read_bytes())
    if len(data) < 0x1B:
        fail(f"crt file too short to patch subtype: {crt_path}")
    data[0x1A] = subtype & 0xFF
    crt_path.write_bytes(bytes(data))
    verify = crt_path.read_bytes()
    if verify[0x1A] != (subtype & 0xFF):
        fail(f"failed to persist crt subtype patch for {crt_path}")


def c_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def parse_catalog(path: Path) -> Dict[str, object]:
    system_cfg, launcher_cfg, apps = apps_catalog.parse_source(str(path))
    entries: List[Dict[str, object]] = []
    for index, pair in enumerate(apps, start=1):
        entry_line, desc = pair
        _drive, prg, label, slot = apps_catalog.parse_app_entry(entry_line, str(path), index)
        entries.append({
            "bank": index,
            "prg": prg,
            "label": label,
            "desc": desc,
            "default_slot": int(slot or "0"),
        })
    return {
        "system": system_cfg,
        "launcher": launcher_cfg,
        "apps": entries,
    }


def payload_len_from_prg(path: Path) -> int:
    raw = path.read_bytes()
    if len(raw) < 3:
        fail(f"payload too short: {path}")
    return len(raw) - 2


def payload_load_from_prg(path: Path) -> int:
    raw = path.read_bytes()
    if len(raw) < 3:
        fail(f"payload too short: {path}")
    return raw[0] | (raw[1] << 8)


def payload_bytes_from_prg(path: Path) -> bytes:
    raw = path.read_bytes()
    if len(raw) < 3:
        fail(f"payload too short: {path}")
    return raw[2:]


def payload_checksum16_from_prg(path: Path) -> int:
    return sum(payload_bytes_from_prg(path)) & 0xFFFF


def launcher_header_text(catalog: Dict[str, object]) -> str:
    apps = list(catalog["apps"])
    lines = [
        "/* Auto-generated by readyos_easyflash.py. Do not edit by hand. */",
        "",
        f'#define READYOS_EASYFLASH_VARIANT_NAME "{c_escape(str(catalog["system"].get("variant_name", "readyos easyflash")))}"',
        f'#define READYOS_EASYFLASH_VARIANT_BOOT_NAME "{c_escape(str(catalog["system"].get("variant_boot_name", "")))}"',
        f'#define READYOS_EASYFLASH_RUNAPPFIRST "{c_escape(str(catalog["launcher"].get("runappfirst", "")))}"',
        f"#define READYOS_EASYFLASH_APP_COUNT {len(apps)}",
        "",
        "static const unsigned char readyos_easyflash_app_banks[READYOS_EASYFLASH_APP_COUNT] = {",
        "    " + ", ".join(str(int(entry["bank"])) for entry in apps),
        "};",
        "",
        "static const unsigned char readyos_easyflash_default_slots[READYOS_EASYFLASH_APP_COUNT] = {",
        "    " + ", ".join(str(int(entry["default_slot"])) for entry in apps),
        "};",
        "",
        "static const char *const readyos_easyflash_prgs[READYOS_EASYFLASH_APP_COUNT] = {",
    ]
    for entry in apps:
        lines.append(f'    "{c_escape(str(entry["prg"]))}",')
    lines.extend([
        "};",
        "",
        "static const char *const readyos_easyflash_labels[READYOS_EASYFLASH_APP_COUNT] = {",
    ])
    for entry in apps:
        lines.append(f'    "{c_escape(str(entry["label"]))}",')
    lines.extend([
        "};",
        "",
        "static const char *const readyos_easyflash_descs[READYOS_EASYFLASH_APP_COUNT] = {",
    ])
    for entry in apps:
        lines.append(f'    "{c_escape(str(entry["desc"]))}",')
    lines.extend([
        "};",
        "",
    ])
    return "\n".join(lines)


def resolve_app_artifact(prg: str) -> Path:
    if prg == "readyshell":
        return BIN_DIR / "readyshell_easyflash.prg"
    return BIN_DIR / f"{prg}.prg"


def build_layout(catalog: Dict[str, object]) -> Dict[str, object]:
    next_bank = 1

    launcher_path = BIN_DIR / "launcher_easyflash.prg"
    launcher_len = payload_len_from_prg(launcher_path)
    launcher_load = payload_load_from_prg(launcher_path)
    if launcher_load != APP_LOAD_START:
        fail(f"launcher_easyflash load address changed: ${launcher_load:04X}")
    launcher_span = int(math.ceil(float(launcher_len) / float(EASYFLASH_PAYLOAD_SLOT_BYTES)))
    layout: Dict[str, object] = {
        "launcher": {
            "artifact": str(launcher_path.relative_to(ROOT)),
            "start_bank": next_bank,
            "bank_span": launcher_span,
            "load_addr": launcher_load,
            "payload_len": launcher_len,
            "checksum16": payload_checksum16_from_prg(launcher_path),
        },
        "apps": [],
        "overlays": [],
    }
    next_bank += launcher_span

    for entry in list(catalog["apps"]):
        app_path = resolve_app_artifact(str(entry["prg"]))
        payload_len = payload_len_from_prg(app_path)
        load_addr = payload_load_from_prg(app_path)
        if load_addr < APP_LOAD_START or load_addr >= (APP_LOAD_START + APP_SNAPSHOT_SIZE):
            fail(f"app load address out of range for {entry['prg']}: ${load_addr:04X}")
        bank_span = int(math.ceil(float(payload_len) / float(EASYFLASH_PAYLOAD_SLOT_BYTES)))
        layout["apps"].append({
            "bank": int(entry["bank"]),
            "prg": str(entry["prg"]),
            "label": str(entry["label"]),
            "artifact": str(app_path.relative_to(ROOT)),
            "start_bank": next_bank,
            "bank_span": bank_span,
            "load_addr": load_addr,
            "payload_len": payload_len,
            "checksum16": payload_checksum16_from_prg(app_path),
            "default_slot": int(entry["default_slot"]),
        })
        next_bank += bank_span

    for name, rel_path, reu_bank, reu_off, valid_bit in OVERLAY_SPECS:
        overlay_path = ROOT / rel_path
        payload_len = payload_len_from_prg(overlay_path)
        load_addr = payload_load_from_prg(overlay_path)
        if load_addr != READYSHELL_OVL_LOAD:
            fail(f"overlay load address changed for {name}: ${load_addr:04X}")
        bank_span = int(math.ceil(float(payload_len) / float(EASYFLASH_PAYLOAD_SLOT_BYTES)))
        layout["overlays"].append({
            "name": name,
            "artifact": str(overlay_path.relative_to(ROOT)),
            "start_bank": next_bank,
            "bank_span": bank_span,
            "load_addr": load_addr,
            "payload_len": payload_len,
            "checksum16": payload_checksum16_from_prg(overlay_path),
            "reu_bank": reu_bank,
            "reu_off": reu_off,
            "valid_bit": valid_bit,
        })
        next_bank += bank_span

    if next_bank > EASYFLASH_TOTAL_BANKS:
        fail(f"easyflash payload exceeds {EASYFLASH_TOTAL_BANKS - 1} data banks")
    layout["last_used_bank"] = next_bank - 1
    return layout


def layout_inc_text(layout: Dict[str, object]) -> str:
    apps = list(layout["apps"])
    overlays = list(layout["overlays"])
    lines = [
        "; Auto-generated by readyos_easyflash.py. Do not edit by hand.",
        "",
        f"EASYFLASH_APP_COUNT = {len(apps)}",
        f"EASYFLASH_OVERLAY_COUNT = {len(overlays)}",
        f"EASYFLASH_LAUNCHER_BANK = {int(layout['launcher']['start_bank'])}",
        f"EASYFLASH_LAUNCHER_BANK_SPAN = {int(layout['launcher']['bank_span'])}",
        f"EASYFLASH_LAUNCHER_LOAD_ADDR = ${int(layout['launcher']['load_addr']):04X}",
        f"EASYFLASH_LAUNCHER_PAYLOAD_LEN = ${int(layout['launcher']['payload_len']):04X}",
        f"EASYFLASH_LAUNCHER_CHECKSUM16 = ${int(layout['launcher']['checksum16']):04X}",
        f"READYSHELL_OVERLAY_STAGE_ADDR = ${APP_LOAD_START:04X}",
        f"READYSHELL_OVERLAY_META_OFF = ${READYSHELL_OVL_META_OFF:06X}",
        "",
        "easyflash_app_table:",
    ]
    for entry in apps:
        lines.append(
            f"    .byte {int(entry['bank'])}, {int(entry['start_bank'])}, {int(entry['bank_span'])}, "
            f"<${int(entry['load_addr']):04X}, >${int(entry['load_addr']):04X}, "
            f"<${int(entry['payload_len']):04X}, >${int(entry['payload_len']):04X}, "
            f"<${int(entry['checksum16']):04X}, >${int(entry['checksum16']):04X}"
        )
    lines.extend([
        "",
        "easyflash_overlay_table:",
    ])
    for entry in overlays:
        lines.append(
            f"    .byte {int(entry['start_bank'])}, {int(entry['bank_span'])}, "
            f"<${int(entry['load_addr']):04X}, >${int(entry['load_addr']):04X}, "
            f"<${int(entry['payload_len']):04X}, >${int(entry['payload_len']):04X}, "
            f"<${int(entry['checksum16']):04X}, >${int(entry['checksum16']):04X}, "
            f"{int(entry['reu_bank'])}, <${int(entry['reu_off']):04X}, >${int(entry['reu_off']):04X}, {int(entry['valid_bit'])}"
        )
    lines.append("")
    return "\n".join(lines)


def build_data_disk(catalog: Dict[str, object], output_path: Path) -> None:
    entries = list(catalog["apps"])
    apps_set = {str(entry["prg"]) for entry in entries}
    readyos_profiles.bootstrap_authoritative_support_files(apps_set)
    ensure_dir(output_path.parent)
    managed_names = {
        str(item["disk_name"]).lower()
        for item in readyos_profiles.authoritative_support_entries(apps_set)
    }
    backup = readyos_profiles.backup_user_files(output_path, managed_names)
    if output_path.exists():
        output_path.unlink()
    readyos_profiles.run(["c1541", "-format", "readyosdata,ro", "d64", str(output_path)])
    for item in readyos_profiles.authoritative_support_entries(apps_set):
        readyos_profiles.write_authoritative_support_file(item, output_path)
    if backup is not None:
        stage_dir, manifest_path = backup
        readyos_profiles.restore_user_files(output_path, manifest_path)
        shutil.rmtree(stage_dir, ignore_errors=True)


def raw_offset(bank: int, addr: int) -> int:
    if addr == 0x8000:
        return bank * EASYFLASH_BANK_BYTES
    if addr == 0xA000:
        return bank * EASYFLASH_BANK_BYTES + EASYFLASH_LOW_BYTES
    fail(f"unsupported easyflash chip address: ${addr:04X}")
    return 0


def compose_easyflash_image(layout: Dict[str, object],
                            roml_path: Path,
                            romh_path: Path,
                            output_path: Path) -> None:
    image = bytearray([0xFF] * EASYFLASH_TOTAL_BYTES)
    roml = roml_path.read_bytes()
    romh = romh_path.read_bytes()
    if len(roml) > EASYFLASH_LOW_BYTES:
        fail(f"loader ROML exceeds 8KiB: {len(roml)}")
    if len(romh) > EASYFLASH_LOW_BYTES:
        fail(f"stub ROMH exceeds 8KiB: {len(romh)}")
    image[raw_offset(0, 0x8000):raw_offset(0, 0x8000) + len(roml)] = roml
    image[raw_offset(0, 0xA000):raw_offset(0, 0xA000) + len(romh)] = romh

    payloads = [layout["launcher"]] + list(layout["apps"]) + list(layout["overlays"])
    for entry in payloads:
        artifact = ROOT / str(entry["artifact"])
        payload = payload_bytes_from_prg(artifact)
        remaining = payload
        bank = int(entry["start_bank"])
        while remaining:
            chunk = remaining[:EASYFLASH_PAYLOAD_SLOT_BYTES]
            remaining = remaining[EASYFLASH_PAYLOAD_SLOT_BYTES:]
            low = chunk[:EASYFLASH_LOW_BYTES]
            high = chunk[EASYFLASH_LOW_BYTES:EASYFLASH_PAYLOAD_SLOT_BYTES]
            start = raw_offset(bank, 0x8000)
            image[start:start + len(low)] = low
            if high:
                high_start = raw_offset(bank, 0xA000)
                image[high_start:high_start + len(high)] = high
            bank += 1

    ensure_dir(output_path.parent)
    output_path.write_bytes(bytes(image))


def build_help_text(output_dir: Path) -> str:
    return "\n".join([
        "# readyos easyflash",
        "",
        "- attach `readyos_easyflash.crt` as an easyflash cartridge",
        "- mount `readyos_data.d64` on drive `8`",
        "- enable reu `16mb`",
        "",
        "## vice example",
        "",
        "```sh",
        "x64sc -reu -reusize 16384 -cartcrt readyos_easyflash.crt -drive8type 1541 -devicebackend8 0 +busdevice8 -8 readyos_data.d64",
        "```",
        "",
    ])


def build_release(catalog_path: Path,
                  layout_path: Path,
                  roml_path: Path,
                  romh_path: Path,
                  version_text: str,
                  output_dir: Path) -> None:
    catalog = parse_catalog(catalog_path)
    layout = json.loads(layout_path.read_text(encoding="utf-8"))
    ensure_dir(output_dir)
    raw_bin = output_dir / "readyos_easyflash.bin"
    crt_path = output_dir / "readyos_easyflash.crt"
    d64_path = output_dir / "readyos_data.d64"
    compose_easyflash_image(layout, roml_path, romh_path, raw_bin)
    run([
        "/opt/homebrew/bin/cartconv",
        "-t", "easy",
        "-s", "1",
        "-i", str(raw_bin),
        "-o", str(crt_path),
        "-n", "readyos easyflash",
    ])
    build_data_disk(catalog, d64_path)
    shutil.copyfile(layout_path, output_dir / "layout.json")
    (output_dir / "helpme.md").write_text(build_help_text(output_dir), encoding="utf-8")
    (output_dir / "help.md").write_text(build_help_text(output_dir), encoding="utf-8")
    manifest = {
        "id": "precog-easyflash",
        "display_name": "precog easyflash",
        "kind": "easyflash",
        "version_text": version_text,
        "catalog_source": str(catalog_path),
        "artifacts": {
            "crt": str(crt_path),
            "data_disk": str(d64_path),
            "raw_bin": str(raw_bin),
            "layout": str(output_dir / "layout.json"),
        },
        "apps": list(catalog["apps"]),
        "launcher": layout["launcher"],
        "overlays": list(layout["overlays"]),
    }
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    force_easyflash_subtype(crt_path, 1)


def verify_layout(catalog: Dict[str, object], layout: Dict[str, object]) -> None:
    apps = list(catalog["apps"])
    layout_apps = list(layout["apps"])
    if len(apps) != len(layout_apps):
        fail("layout app count mismatch")
    for source, packed in zip(apps, layout_apps):
        if str(source["prg"]) != str(packed["prg"]):
            fail(f"layout order mismatch for app {source['prg']}")
        if int(source["bank"]) != int(packed["bank"]):
            fail(f"layout bank mismatch for app {source['prg']}")


def verify_release(catalog_path: Path, layout_path: Path, output_dir: Path) -> None:
    catalog = parse_catalog(catalog_path)
    layout = json.loads(layout_path.read_text(encoding="utf-8"))
    verify_layout(catalog, layout)

    crt_path = output_dir / "readyos_easyflash.crt"
    d64_path = output_dir / "readyos_data.d64"
    header_path = GEN_DIR / "launcher_easyflash_catalog.h"

    if not crt_path.exists():
        fail(f"missing crt artifact: {crt_path}")
    if not d64_path.exists():
        fail(f"missing data disk: {d64_path}")
    if not header_path.exists():
        fail(f"missing generated launcher header: {header_path}")
    if not (ROOT / "obj" / "launcher_easyflash.map").exists():
        fail("missing launcher_easyflash map")
    if not (ROOT / "obj" / "readyshell_easyflash.map").exists():
        fail("missing readyshell_easyflash map")

    run(["/opt/homebrew/bin/cartconv", "-c", str(crt_path)])
    info = subprocess.run(
        ["/opt/homebrew/bin/cartconv", "-f", str(crt_path)],
        cwd=str(ROOT),
        check=True,
        text=True,
        capture_output=True,
    )
    info_text = info.stdout.lower()
    if "hardware id: 32 (easyflash)" not in info_text:
        fail("crt type is not easyflash")
    if "hardware revision: 1" not in info_text:
        if "hardware revision: 0" in info_text:
            print(
                "warning: cartconv reports hardware revision 0 for this EasyFlash CRT "
                "even though the build requested revision/subtype 1",
                file=sys.stderr,
            )
        else:
            fail("crt subtype is not 1")

    for payload in [layout["launcher"]] + list(layout["apps"]) + list(layout["overlays"]):
        artifact = ROOT / str(payload["artifact"])
        if not artifact.exists():
            fail(f"missing packed payload artifact: {artifact}")

    expected_names = {
        str(item["disk_name"]).lower()
        for item in readyos_profiles.authoritative_support_entries(
            {str(entry["prg"]) for entry in catalog["apps"]}
        )
    }
    expected_types = {
        str(item["disk_name"]).lower(): str(item["type"]).lower()
        for item in readyos_profiles.authoritative_support_entries(
            {str(entry["prg"]) for entry in catalog["apps"]}
        )
    }
    listing = readyos_profiles.list_seq_rel_files(d64_path)
    seen = {str(item["disk_name"]).lower(): str(item["type"]).lower() for item in listing}
    if set(seen.keys()) != expected_names:
        fail("data disk contents do not match expected runtime-data set")
    for name, file_type in seen.items():
        if expected_types[name] != file_type:
            fail(f"data disk type mismatch for {name}")

    source_header = launcher_header_text(catalog)
    actual_header = header_path.read_text(encoding="utf-8")
    if source_header.strip() != actual_header.strip():
        fail("generated launcher header is out of sync with catalog source")

    baseline_size = payload_len_from_prg(BIN_DIR / "readyshell.prg")
    easyflash_size = payload_len_from_prg(BIN_DIR / "readyshell_easyflash.prg")
    if easyflash_size > baseline_size + 512:
        fail(
            f"readyshell_easyflash payload grew too much vs baseline "
            f"({easyflash_size} > {baseline_size} + 512)"
        )


def fmt_kib(value: int) -> str:
    return f"{value / 1024.0:6.1f} KiB"


def fmt_pct(used: int, total: int) -> str:
    if total <= 0:
        return "  0.0%"
    return f"{(100.0 * float(used) / float(total)):5.1f}%"


def make_bar(used: int, total: int, width: int) -> str:
    if width <= 0 or total <= 0:
        return "." * max(width, 0)
    filled = int(round((float(used) / float(total)) * float(width)))
    if used > 0 and filled == 0:
        filled = 1
    if used >= total:
        filled = width
    filled = max(0, min(width, filled))
    return "#" * filled + "." * (width - filled)


def payload_entries(layout: Dict[str, object]) -> List[Dict[str, object]]:
    entries: List[Dict[str, object]] = []
    entries.append({
        "kind": "launcher",
        "symbol": "L",
        "name": "launcher",
        **dict(layout["launcher"]),
    })

    symbol_index = 0
    for entry in list(layout["apps"]):
        if symbol_index >= len(REPORT_SYMBOLS):
            fail("report symbol table exhausted for apps")
        entries.append({
            "kind": "app",
            "symbol": REPORT_SYMBOLS[symbol_index],
            "name": str(entry["label"]),
            **dict(entry),
        })
        symbol_index += 1

    for entry in list(layout["overlays"]):
        if symbol_index >= len(REPORT_SYMBOLS):
            fail("report symbol table exhausted for overlays")
        entries.append({
            "kind": "overlay",
            "symbol": REPORT_SYMBOLS[symbol_index],
            "name": str(entry["name"]),
            **dict(entry),
        })
        symbol_index += 1
    return entries


def render_easyflash_report(layout: Dict[str, object],
                            *,
                            title: str,
                            roml_size: int = 0,
                            romh_size: int = 0) -> str:
    entries = payload_entries(layout)
    cells = ["."] * EASYFLASH_TOTAL_BANKS
    names = ["free"] * EASYFLASH_TOTAL_BANKS
    cells[0] = "B"
    names[0] = "boot"

    for entry in entries:
        start_bank = int(entry["start_bank"])
        bank_span = int(entry["bank_span"])
        for bank in range(start_bank, start_bank + bank_span):
            if bank < 0 or bank >= EASYFLASH_TOTAL_BANKS:
                fail(f"report bank out of range: {bank}")
            if cells[bank] != ".":
                fail(f"report bank overlap at {bank}")
            cells[bank] = str(entry["symbol"])
            names[bank] = str(entry["name"])

    last_used_bank = int(layout.get("last_used_bank", 0))
    used_payload_banks = max(0, last_used_bank)
    free_payload_banks = max(0, (EASYFLASH_TOTAL_BANKS - 1) - used_payload_banks)
    used_total_banks = 1 + used_payload_banks
    free_total_banks = EASYFLASH_TOTAL_BANKS - used_total_banks

    payload_bytes = 0
    reserved_payload_bytes = 0
    for entry in entries:
        payload_bytes += int(entry["payload_len"])
        reserved_payload_bytes += int(entry["bank_span"]) * EASYFLASH_PAYLOAD_SLOT_BYTES
    payload_slack_bytes = reserved_payload_bytes - payload_bytes

    boot_payload_bytes = roml_size + romh_size
    boot_reserved_bytes = EASYFLASH_BANK_BYTES
    boot_slack_bytes = max(0, boot_reserved_bytes - boot_payload_bytes)

    used_total_bytes = payload_bytes + boot_payload_bytes
    reserved_total_bytes = used_total_banks * EASYFLASH_BANK_BYTES
    total_slack_bytes = reserved_total_bytes - used_total_bytes

    lines: List[str] = []
    inner_width = 76

    def rule() -> str:
        return "+" + ("-" * inner_width) + "+"

    def boxed(text: str = "") -> str:
        clipped = text[:inner_width]
        return "| " + clipped.ljust(inner_width - 2) + " |"

    lines.append(rule())
    lines.append(boxed(title.upper()))
    lines.append(rule())
    lines.append(boxed(
        f"Cartridge size : {EASYFLASH_TOTAL_BANKS:2d} banks x 16 KiB = {EASYFLASH_TOTAL_BYTES // 1024:4d} KiB"
    ))
    lines.append(boxed(
        f"Total used     : {used_total_banks:2d}/{EASYFLASH_TOTAL_BANKS:2d} banks ({fmt_pct(used_total_banks, EASYFLASH_TOTAL_BANKS)})  "
        f"free {free_total_banks:2d}"
    ))
    lines.append(boxed(
        f"Payload banks  : {used_payload_banks:2d}/63 banks ({fmt_pct(used_payload_banks, 63)})  "
        f"free {free_payload_banks:2d}"
    ))
    lines.append(boxed(
        f"Actual bytes   : {fmt_kib(used_total_bytes)} used  / {fmt_kib(EASYFLASH_TOTAL_BYTES)} total"
    ))
    lines.append(boxed(
        f"Reserved bytes : {fmt_kib(reserved_total_bytes)} packed  / slack {fmt_kib(total_slack_bytes)}"
    ))
    lines.append(boxed(
        f"Payload fill   : {fmt_kib(payload_bytes)} data  / {fmt_kib(reserved_payload_bytes)} packed  / slack {fmt_kib(payload_slack_bytes)}"
    ))
    lines.append(boxed(
        f"Boot fill      : {fmt_kib(boot_payload_bytes)} ROML+ROMH / {fmt_kib(boot_reserved_bytes)} bank  / slack {fmt_kib(boot_slack_bytes)}"
    ))
    lines.append(boxed(
        f"Utilization    : [{make_bar(used_total_banks, EASYFLASH_TOTAL_BANKS, 48)}] {fmt_pct(used_total_banks, EASYFLASH_TOTAL_BANKS)}"
    ))
    lines.append(rule())
    lines.append(boxed("Bank Map"))
    for row_start in range(0, EASYFLASH_TOTAL_BANKS, 8):
        row = " ".join(f"{bank:02d}:{cells[bank]}" for bank in range(row_start, row_start + 8))
        lines.append(boxed(row))
    lines.append(rule())
    lines.append(boxed("Legend"))
    lines.append(boxed("  B boot bank    L launcher    1..Z/a..z apps and overlays    . free"))
    for entry in entries:
        start_bank = int(entry["start_bank"])
        end_bank = start_bank + int(entry["bank_span"]) - 1
        reserved = int(entry["bank_span"]) * EASYFLASH_PAYLOAD_SLOT_BYTES
        fill_pct = fmt_pct(int(entry["payload_len"]), reserved)
        bank_range = f"{start_bank:02d}" if start_bank == end_bank else f"{start_bank:02d}-{end_bank:02d}"
        kind = str(entry["kind"]).ljust(8)
        symbol = str(entry["symbol"])
        name = str(entry["name"])[:24].ljust(24)
        lines.append(boxed(
            f"  {symbol} {kind} {bank_range:>5}  {fmt_kib(int(entry['payload_len']))} / {fmt_kib(reserved)}  {fill_pct}  {name}"
        ))
    lines.append(rule())
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    header_parser = sub.add_parser("catalog-header")
    header_parser.add_argument("--catalog", required=True)
    header_parser.add_argument("--output", required=True)

    layout_parser = sub.add_parser("layout")
    layout_parser.add_argument("--catalog", required=True)
    layout_parser.add_argument("--json-output", required=True)
    layout_parser.add_argument("--asm-output", required=True)

    release_parser = sub.add_parser("build-release")
    release_parser.add_argument("--catalog", required=True)
    release_parser.add_argument("--layout", required=True)
    release_parser.add_argument("--roml", required=True)
    release_parser.add_argument("--romh", required=True)
    release_parser.add_argument("--version", required=True)
    release_parser.add_argument("--output-dir", required=True)

    verify_parser = sub.add_parser("verify-release")
    verify_parser.add_argument("--catalog", required=True)
    verify_parser.add_argument("--layout", required=True)
    verify_parser.add_argument("--output-dir", required=True)

    report_parser = sub.add_parser("report")
    report_parser.add_argument("--layout", default=str(OBJ_DIR / "easyflash_layout.json"))
    report_parser.add_argument("--roml", default=str(BIN_DIR / "boot_easyflash_roml.bin"))
    report_parser.add_argument("--romh", default=str(BIN_DIR / "boot_easyflash_romh.bin"))
    report_parser.add_argument("--title", default="ReadyOS EasyFlash Usage")

    args = ap.parse_args()

    try:
        if args.cmd == "catalog-header":
            catalog = parse_catalog(Path(args.catalog))
            output = Path(args.output)
            ensure_dir(output.parent)
            output.write_text(launcher_header_text(catalog), encoding="utf-8")
            return 0
        if args.cmd == "layout":
            catalog = parse_catalog(Path(args.catalog))
            layout = build_layout(catalog)
            json_output = Path(args.json_output)
            asm_output = Path(args.asm_output)
            ensure_dir(json_output.parent)
            ensure_dir(asm_output.parent)
            json_output.write_text(json.dumps(layout, indent=2) + "\n", encoding="utf-8")
            asm_output.write_text(layout_inc_text(layout), encoding="utf-8")
            return 0
        if args.cmd == "build-release":
            build_release(
                Path(args.catalog),
                Path(args.layout),
                Path(args.roml),
                Path(args.romh),
                args.version,
                Path(args.output_dir),
            )
            return 0
        if args.cmd == "verify-release":
            verify_release(Path(args.catalog), Path(args.layout), Path(args.output_dir))
            return 0
        if args.cmd == "report":
            layout = json.loads(Path(args.layout).read_text(encoding="utf-8"))
            roml_path = Path(args.roml)
            romh_path = Path(args.romh)
            roml_size = roml_path.stat().st_size if roml_path.exists() else 0
            romh_size = romh_path.stat().st_size if romh_path.exists() else 0
            print(render_easyflash_report(
                layout,
                title=args.title,
                roml_size=roml_size,
                romh_size=romh_size,
            ))
            return 0
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
