#!/usr/bin/env python3
"""
Standalone EasyFlash + REU proof harness for ReadyOS.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import select
import socket
import subprocess
import sys
import time
from pathlib import Path

import readyos_easyflash


ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = ROOT / "bin"
OBJ_DIR = ROOT / "obj"
GEN_DIR = ROOT / "src" / "generated"
ARTIFACT_DIR = ROOT / "artifacts" / "dev_harness" / "xefprobe"

HOST_CART_BANK = 1
PAYLOAD_CART_BANK = 2
DATA_CART_BANK = 3

HOST_REU_BANK = 0
PAYLOAD_REU_BANK = 1
DATA_REU_BANK = 2
SCRATCH_REU_BANK = 3

DATA_LEN = 256
CRT_SUBTYPE_OFFSET = 0x1A
XEFPROBE_HOST_FLAG = 0x48
XEFPROBE_HOST_DATA_FLAG = 0x56
XEFPROBE_PAYLOAD_FLAG = 0x50
XEFPROBE_STASH_FLAG = 0x53
STOP_SUCCESS_ADDR = 0xC7F8
STOP_FAIL_ADDR = 0xC7FA


def fail(message: str) -> None:
    raise ValueError(message)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, cwd=str(ROOT), check=True, text=True)


def payload_len_from_prg(path: Path) -> int:
    return readyos_easyflash.payload_len_from_prg(path)


def payload_bytes_from_prg(path: Path) -> bytes:
    return readyos_easyflash.payload_bytes_from_prg(path)


def pattern_byte(index: int) -> int:
    return (0x33 + ((index & 0xFF) * 5)) & 0xFF


def build_data_blob(path: Path) -> bytes:
    data = bytes(pattern_byte(i) for i in range(DATA_LEN))
    ensure_dir(path.parent)
    path.write_bytes(data)
    return data


def layout_dict(host_path: Path, payload_path: Path, data_path: Path) -> dict[str, object]:
    host_path = host_path.resolve()
    payload_path = payload_path.resolve()
    data_path = data_path.resolve()
    return {
        "host": {
            "artifact": str(host_path.relative_to(ROOT)),
            "cart_bank": HOST_CART_BANK,
            "reu_bank": HOST_REU_BANK,
            "payload_len": payload_len_from_prg(host_path),
        },
        "payload": {
            "artifact": str(payload_path.relative_to(ROOT)),
            "cart_bank": PAYLOAD_CART_BANK,
            "reu_bank": PAYLOAD_REU_BANK,
            "payload_len": payload_len_from_prg(payload_path),
        },
        "data": {
            "artifact": str(data_path.relative_to(ROOT)),
            "cart_bank": DATA_CART_BANK,
            "reu_bank": DATA_REU_BANK,
            "payload_len": DATA_LEN,
        },
        "scratch_reu_bank": SCRATCH_REU_BANK,
    }


def layout_inc_text(layout: dict[str, object]) -> str:
    return "\n".join([
        "; Auto-generated by readyos_easyflash_probe.py. Do not edit by hand.",
        "",
        f"XEFPROBE_HOST_CART_BANK = {int(layout['host']['cart_bank'])}",
        f"XEFPROBE_HOST_PAYLOAD_LEN = ${int(layout['host']['payload_len']):04X}",
        f"XEFPROBE_PAYLOAD_CART_BANK = {int(layout['payload']['cart_bank'])}",
        f"XEFPROBE_PAYLOAD_LEN = ${int(layout['payload']['payload_len']):04X}",
        f"XEFPROBE_DATA_CART_BANK = {int(layout['data']['cart_bank'])}",
        f"XEFPROBE_DATA_LEN = ${int(layout['data']['payload_len']):04X}",
        "",
    ])


def compose_image(layout: dict[str, object], roml_path: Path, romh_path: Path, output_path: Path) -> None:
    image = bytearray([0xFF] * readyos_easyflash.EASYFLASH_TOTAL_BYTES)
    roml = roml_path.read_bytes()
    romh = romh_path.read_bytes()
    if len(roml) > readyos_easyflash.EASYFLASH_LOW_BYTES:
        fail(f"probe loader ROML exceeds 8KiB: {len(roml)}")
    if len(romh) > readyos_easyflash.EASYFLASH_LOW_BYTES:
        fail(f"probe stub ROMH exceeds 8KiB: {len(romh)}")
    image[0:len(roml)] = roml
    image[readyos_easyflash.EASYFLASH_LOW_BYTES:readyos_easyflash.EASYFLASH_LOW_BYTES + len(romh)] = romh

    payload_specs = [
        (int(layout["host"]["cart_bank"]), payload_bytes_from_prg(ROOT / str(layout["host"]["artifact"]))),
        (int(layout["payload"]["cart_bank"]), payload_bytes_from_prg(ROOT / str(layout["payload"]["artifact"]))),
        (int(layout["data"]["cart_bank"]), (ROOT / str(layout["data"]["artifact"])).read_bytes()),
    ]
    for bank, payload in payload_specs:
        low = payload[:readyos_easyflash.EASYFLASH_LOW_BYTES]
        high = payload[readyos_easyflash.EASYFLASH_LOW_BYTES:readyos_easyflash.EASYFLASH_PAYLOAD_SLOT_BYTES]
        base = bank * readyos_easyflash.EASYFLASH_BANK_BYTES
        image[base:base + len(low)] = low
        if high:
            high_base = base + readyos_easyflash.EASYFLASH_LOW_BYTES
            image[high_base:high_base + len(high)] = high

    ensure_dir(output_path.parent)
    output_path.write_bytes(bytes(image))


def build_release(layout_path: Path, roml_path: Path, romh_path: Path, output_dir: Path) -> None:
    layout = json.loads(layout_path.read_text(encoding="utf-8"))
    ensure_dir(output_dir)
    raw_bin = output_dir / "xefprobe.bin"
    crt_path = output_dir / "xefprobe.crt"
    d64_path = output_dir / "xefprobe_data.d64"

    compose_image(layout, roml_path, romh_path, raw_bin)
    run([
        "/opt/homebrew/bin/cartconv",
        "-t", "easy",
        "-s", "1",
        "-i", str(raw_bin),
        "-o", str(crt_path),
        "-n", "xefprobe",
    ])
    note_path = output_dir / "xefprobe_notice.txt"
    note_path.write_text("XEFPROBE PLACEHOLDER DRIVE 8\n", encoding="ascii")
    if d64_path.exists():
        d64_path.unlink()
    run(["c1541", "-format", "xefprobe8,ro", "d64", str(d64_path)])
    run(["c1541", str(d64_path), "-write", str(note_path), "notice,s"])
    manifest = {
        "id": "xefprobe",
        "kind": "easyflash-probe",
        "artifacts": {
            "crt": str(crt_path),
            "data_disk": str(d64_path),
            "raw_bin": str(raw_bin),
            "layout": str(layout_path),
        },
        "layout": layout,
    }
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (output_dir / "helpme.md").write_text(
        "\n".join([
            "# xefprobe",
            "",
            "```sh",
            f"x64sc -reu -reusize 16384 -cartcrt {crt_path} -drive8type 1541 -devicebackend8 0 +busdevice8 -8 {d64_path}",
            "```",
            "",
        ]),
        encoding="utf-8",
    )
    readyos_easyflash.force_easyflash_subtype(crt_path, 1)


def write_monitor(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join([
            f"break ${STOP_SUCCESS_ADDR:04x}",
            f"break ${STOP_FAIL_ADDR:04x}",
            "x",
            "m 0400 047f",
            "m c7a0 c7ef",
            "m c7e8 c7ef",
            "q",
            "",
        ]),
        encoding="ascii",
    )


def parse_monitor_log(path: Path) -> dict[int, bytes]:
    dumps: dict[int, bytes] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"^>?\s*[.>]?C:([0-9a-fA-F]{4})\s+(.*)$", line)
        if not match:
            continue
        addr = int(match.group(1), 16)
        values = re.findall(r"\b([0-9a-fA-F]{2})\b", match.group(2))
        if values:
            dumps[addr] = bytes(int(value, 16) for value in values)
    return dumps


def region_bytes(dumps: dict[int, bytes], start: int, length: int) -> bytes:
    out = bytearray()
    cursor = start
    while len(out) < length:
        chunk = dumps.get(cursor)
        if not chunk:
            break
        out.extend(chunk)
        cursor += len(chunk)
    return bytes(out[:length])


def ascii_to_screen(text: str) -> bytes:
    out = bytearray()
    for ch in text:
        if "A" <= ch <= "Z":
            out.append(ord(ch) - ord("A") + 1)
        elif "0" <= ch <= "9":
            out.append(ord(ch) - ord("0") + 48)
        elif ch == " ":
            out.append(32)
        elif ch == "-":
            out.append(45)
        else:
            out.append(32)
    return bytes(out)


def verify_release(output_dir: Path) -> None:
    crt_path = output_dir / "xefprobe.crt"
    d64_path = output_dir / "xefprobe_data.d64"
    if not crt_path.exists():
        fail(f"missing probe crt: {crt_path}")
    if not d64_path.exists():
        fail(f"missing probe data disk: {d64_path}")
    data = crt_path.read_bytes()
    if len(data) <= CRT_SUBTYPE_OFFSET:
        fail("crt too short to verify subtype")
    if data[CRT_SUBTYPE_OFFSET] != 1:
        fail(f"crt subtype byte is {data[CRT_SUBTYPE_OFFSET]}, expected 1")
    run(["/opt/homebrew/bin/cartconv", "-c", str(crt_path)])


def verify_log(host_map: Path, payload_map: Path, log_path: Path) -> None:
    _ = host_map
    _ = payload_map
    text = log_path.read_text(encoding="utf-8", errors="replace")
    if f"C:${STOP_FAIL_ADDR:04X}" in text.upper() or f"C:{STOP_FAIL_ADDR:04X}" in text.upper():
        fail(f"probe stopped in fail trap at ${STOP_FAIL_ADDR:04X}")
    if f"C:${STOP_SUCCESS_ADDR:04X}" not in text.upper() and f"C:{STOP_SUCCESS_ADDR:04X}" not in text.upper():
        fail(f"probe success trap at ${STOP_SUCCESS_ADDR:04X} was not reached")

    dumps = parse_monitor_log(log_path)
    screen = region_bytes(dumps, 0x0400, 0x80)
    results = region_bytes(dumps, 0xC7E8, 8)
    if len(screen) < 16:
        fail("missing screen dump in monitor log")
    if len(results) < 4:
        fail("missing result-byte dump in monitor log")

    expected_title = ascii_to_screen("XEFPROBE PAYLOAD")
    if screen[:len(expected_title)] != expected_title:
        fail("payload screen title mismatch")

    expected_results = bytes([
        XEFPROBE_HOST_FLAG,
        XEFPROBE_HOST_DATA_FLAG,
        XEFPROBE_PAYLOAD_FLAG,
        XEFPROBE_STASH_FLAG,
    ])
    if results[:4] != expected_results:
        fail(
            "result flags mismatch: "
            f"expected {expected_results.hex(' ')}, saw {results[:4].hex(' ')}"
        )

    ring = region_bytes(dumps, 0xC7A0, 0x50)
    for marker in (b"H", b"C", b"V", b"L", b"P", b"D", b"S"):
        if marker[0] not in ring:
            fail(f"debug ring missing marker {marker.decode('ascii')}")
    if ord("F") in ring:
        fail("debug ring shows failure marker F")

    print("xefprobe verify-log passed")
    print(f"  stop_success: ${STOP_SUCCESS_ADDR:04X}")
    print(f"  result flags: {results[:4].hex(' ')}")


def read_until_quiet(sock: socket.socket,
                     quiet_seconds: float = 0.25,
                     timeout_seconds: float = 8.0) -> str:
    deadline = time.time() + timeout_seconds
    last_data_at = time.time()
    chunks: list[bytes] = []
    while time.time() < deadline:
        wait = max(0.05, min(0.2, deadline - time.time()))
        ready, _, _ = select.select([sock], [], [], wait)
        if ready:
            chunk = sock.recv(65536)
            if not chunk:
                break
            chunks.append(chunk)
            last_data_at = time.time()
            continue
        if chunks and (time.time() - last_data_at) >= quiet_seconds:
            break
    return b"".join(chunks).decode("utf-8", errors="replace")


def send_command(sock: socket.socket, command: str) -> str:
    sock.sendall(command.encode("ascii") + b"\n")
    return read_until_quiet(sock)


def wait_for_text(sock: socket.socket, needles: list[str], timeout_seconds: float = 15.0) -> str:
    deadline = time.time() + timeout_seconds
    chunks: list[str] = []
    while time.time() < deadline:
        chunk = read_until_quiet(sock, quiet_seconds=0.15, timeout_seconds=1.0)
        if chunk:
            chunks.append(chunk)
            merged = "".join(chunks)
            for needle in needles:
                if needle in merged:
                    return merged
    raise RuntimeError(f"timed out waiting for monitor text: {needles!r}")


def connect_with_retry(host: str, port: int, timeout_seconds: float = 15.0) -> socket.socket:
    deadline = time.time() + timeout_seconds
    last_error: OSError | None = None
    while time.time() < deadline:
        try:
            return socket.create_connection((host, port), timeout=2.0)
        except OSError as exc:
            last_error = exc
            time.sleep(0.2)
    if last_error is not None:
        raise last_error
    raise RuntimeError("remote monitor connection failed")


def runtime_verify(vice_cmd: str,
                   crt_path: Path,
                   d64_path: Path,
                   host_map: Path,
                   payload_map: Path,
                   log_path: Path,
                   vice_stdout_path: Path,
                   remote_addr: str) -> None:
    _ = host_map
    _ = payload_map
    host, port_text = remote_addr.rsplit(":", 1)
    port = int(port_text)
    ensure_dir(log_path.parent)
    ensure_dir(vice_stdout_path.parent)

    vice_args = [
        vice_cmd,
        "-console",
        "-default",
        "+sound",
        "-warp",
        "-reu",
        "-reusize", "16384",
        "-cartcrt", str(crt_path),
        "-drive8type", "1541",
        "-devicebackend8", "0",
        "+busdevice8",
        "-8", str(d64_path),
        "-remotemonitor",
        "-remotemonitoraddress", remote_addr,
        "-initbreak", "0xe000",
        "-limitcycles", "30000000",
    ]

    transcript_parts: list[str] = []
    failure_text = ""
    sock: socket.socket | None = None
    with vice_stdout_path.open("w", encoding="utf-8", errors="replace") as vice_out:
        proc = subprocess.Popen(
            vice_args,
            cwd=str(ROOT),
            stdout=vice_out,
            stderr=subprocess.STDOUT,
            text=True,
        )
        try:
            sock = connect_with_retry(host, port, timeout_seconds=15.0)
        except OSError:
            proc.terminate()
            proc.wait(timeout=5)
            raise

        try:
            with sock:
                sock.setblocking(False)
                transcript_parts.append(read_until_quiet(sock, quiet_seconds=0.5, timeout_seconds=8.0))
                transcript_parts.append(send_command(sock, f"break ${STOP_SUCCESS_ADDR:04x}"))
                transcript_parts.append(send_command(sock, f"break ${STOP_FAIL_ADDR:04x}"))
                sock.sendall(b"x\n")
                transcript_parts.append(
                    wait_for_text(
                        sock,
                        [
                            f"C:${STOP_SUCCESS_ADDR:04x}", f"C:{STOP_SUCCESS_ADDR:04x}",
                            f"C:${STOP_SUCCESS_ADDR:04X}", f"C:{STOP_SUCCESS_ADDR:04X}",
                            f"C:${STOP_FAIL_ADDR:04x}", f"C:{STOP_FAIL_ADDR:04x}",
                            f"C:${STOP_FAIL_ADDR:04X}", f"C:{STOP_FAIL_ADDR:04X}",
                        ],
                        timeout_seconds=20.0,
                    )
                )
                transcript_parts.append(send_command(sock, "m $0400 $047f"))
                transcript_parts.append(send_command(sock, "m $c7a0 $c7ef"))
                transcript_parts.append(send_command(sock, "m $c7e8 $c7ef"))
                transcript_parts.append(send_command(sock, "q"))
        except Exception as exc:
            if sock is not None:
                try:
                    transcript_parts.append(send_command(sock, "stop"))
                except Exception:
                    pass
                try:
                    transcript_parts.append(send_command(sock, "m $0400 $047f"))
                    transcript_parts.append(send_command(sock, "m $c7a0 $c7ef"))
                    transcript_parts.append(send_command(sock, "m $c7e8 $c7ef"))
                    transcript_parts.append(send_command(sock, "q"))
                except Exception:
                    pass
            failure_text = f"\n[runtime-verify-exception] {exc!r}\n"
        finally:
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
                    proc.wait(timeout=5)

    transcript = "".join(transcript_parts) + failure_text
    log_path.write_text(transcript, encoding="utf-8")
    if failure_text:
        fail(f"runtime verify monitor session failed: {failure_text.strip()}")
    verify_log(host_map, payload_map, log_path)


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    layout_parser = sub.add_parser("layout")
    layout_parser.add_argument("--host", required=True)
    layout_parser.add_argument("--payload", required=True)
    layout_parser.add_argument("--data-output", required=True)
    layout_parser.add_argument("--json-output", required=True)
    layout_parser.add_argument("--asm-output", required=True)

    build_parser = sub.add_parser("build-release")
    build_parser.add_argument("--layout", required=True)
    build_parser.add_argument("--roml", required=True)
    build_parser.add_argument("--romh", required=True)
    build_parser.add_argument("--output-dir", required=True)

    verify_parser = sub.add_parser("verify-release")
    verify_parser.add_argument("--output-dir", required=True)

    monitor_parser = sub.add_parser("write-monitor")
    monitor_parser.add_argument("--output", required=True)

    log_parser = sub.add_parser("verify-log")
    log_parser.add_argument("--host-map", required=True)
    log_parser.add_argument("--payload-map", required=True)
    log_parser.add_argument("--log", required=True)

    runtime_parser = sub.add_parser("runtime-verify")
    runtime_parser.add_argument("--crt", required=True)
    runtime_parser.add_argument("--d64", required=True)
    runtime_parser.add_argument("--host-map", required=True)
    runtime_parser.add_argument("--payload-map", required=True)
    runtime_parser.add_argument("--log", required=True)
    runtime_parser.add_argument("--vice-stdout", required=True)
    runtime_parser.add_argument("--vice", default=os.environ.get("VICE", "x64sc"))
    runtime_parser.add_argument("--remote-addr", default="127.0.0.1:6510")

    args = ap.parse_args()

    try:
        if args.cmd == "layout":
            host_path = Path(args.host)
            payload_path = Path(args.payload)
            data_path = Path(args.data_output)
            build_data_blob(data_path)
            layout = layout_dict(host_path, payload_path, data_path)
            Path(args.json_output).write_text(json.dumps(layout, indent=2) + "\n", encoding="utf-8")
            Path(args.asm_output).write_text(layout_inc_text(layout), encoding="utf-8")
            return 0
        if args.cmd == "build-release":
            build_release(
                layout_path=Path(args.layout),
                roml_path=Path(args.roml),
                romh_path=Path(args.romh),
                output_dir=Path(args.output_dir),
            )
            return 0
        if args.cmd == "verify-release":
            verify_release(Path(args.output_dir))
            return 0
        if args.cmd == "write-monitor":
            write_monitor(Path(args.output))
            return 0
        if args.cmd == "verify-log":
            verify_log(Path(args.host_map), Path(args.payload_map), Path(args.log))
            return 0
        if args.cmd == "runtime-verify":
            runtime_verify(
                vice_cmd=args.vice,
                crt_path=Path(args.crt),
                d64_path=Path(args.d64),
                host_map=Path(args.host_map),
                payload_map=Path(args.payload_map),
                log_path=Path(args.log),
                vice_stdout_path=Path(args.vice_stdout),
                remote_addr=args.remote_addr,
            )
            return 0
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
